services:
  jupyter:  # you can change this to whatever you want.
    container_name: machine-learning-workspace
    image: tensorflow/tensorflow:latest-gpu-jupyter
    volumes:
      - "./:/tf/notebooks"
    ports:
     - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
          -  driver: nvidia
             count: all
             capabilities: [gpu]